title: Jacob May # your name (or website title) here
logo: images/oooo.plus_10.png # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Current: Halo 
  Previous Bylines: Sports Illustrated (digital), Northwestern University Athletic Department, The Metro-West Daily News, The Standard-Times and North By Northwestern Magazine 
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-may-921868155/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
